server {
    listen 80;
    server_name guiBiblio;
    root /usr/share/nginx/html;
    index index.html index.html;

    location /swagger-ui.html {
        proxy_pass http://provider.app:8090/swagger-ui.html;
    }

    location /api/ {
        proxy_pass http://provider.app:8090/api/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
